export const translations = {
  "es": {
    "navServices": "Servicios",
    "navAbout": "Nosotros",
    "navProcess": "Proceso",
    "navWork": "Ejemplos",
    "navContact": "Contacto",
    "navCta": "Hablemos",
    "heroOne": "Tecnología que se adapta",
    "heroTwo": "a tu negocio.",
    "heroBody": "En Saravia Software creamos sitios web, herramientas e IA para pequeños y medianos negocios. Primero entendemos cómo trabajás; después construimos algo simple, útil y hecho para vos.",
    "heroCta": "Contanos qué necesitás",
    "heroSecondary": "Conocé los servicios",
    "heroNote": "Una conversación clara, desde la primera idea.",
    "heroBottom": "PENSADO PARA NEGOCIOS REALES",
    "introLabel": "NUESTRA FORMA DE TRABAJAR",
    "introOne": "Tu negocio tiene su propia manera de hacer las cosas.",
    "introTwo": "Tu tecnología también debería.",
    "introBody": "No necesitás una plataforma enorme para resolver un problema concreto. Nos sentamos a entender tu día a día y armamos una solución del tamaño justo, con las funciones que realmente vas a usar.",
    "servicesLabel": "CÓMO PODEMOS AYUDARTE",
    "servicesTitle": "Soluciones para tu negocio.",
    "servicesIntro": "Podés empezar por una web para que te encuentren o por una herramienta para trabajar mejor. Lo definimos juntos.",
    "serviceWebTitle": "Sitios web que te encuentran",
    "serviceWeb": "Mostrá lo que hacés, aparecé en búsquedas y facilitá consultas por WhatsApp. Te explicamos el contenido, SEO y las visitas sin tecnicismos.",
    "serviceCustomTitle": "Software a tu medida",
    "serviceCustom": "Stock, turnos o gestión interna según cómo trabajás hoy. Elegís qué necesitás ver y qué pasos te resultan cómodos.",
    "serviceAiTitle": "Asistentes con IA",
    "serviceAi": "Consultá datos de tu negocio desde el celular, pedí reportes o cargá información mediante un chat, con revisión antes de guardar cambios.",
    "serviceSaasTitle": "Herramientas para crecer",
    "serviceSaas": "Empezá con lo esencial y sumá funciones cuando tu negocio las necesite. Una solución proporcionada a tu operación.",
    "serviceDataTitle": "Tus datos, más claros",
    "serviceData": "Visualizá stock, consultas y resultados en pantallas fáciles de entender, para decidir con información a mano.",
    "serviceDesignTitle": "Diseño que te resulte cómodo",
    "serviceDesign": "Probamos cómo se usa cada pantalla con vos: qué aparece primero, cómo se llaman las cosas y qué detalles importan a tu equipo.",
    "capLabel": "LO QUE GANÁS CON ESTO",
    "capWeb": "Una presencia online que explica qué ofrecés y cómo contactarte.",
    "capSaas": "Empezá con lo que necesitás; agregá funciones a medida que crezcas.",
    "capAi": "Hacé preguntas sobre tu negocio desde el celular.",
    "capAutomation": "Dedicá menos tiempo a tareas repetitivas.",
    "capDashboards": "Encontrá los datos importantes sin revisar planillas eternas.",
    "capProduct": "Una herramienta que tu equipo sepa usar todos los días.",
    "capWebTitle": "WEB",
    "capSaasTitle": "CRECER",
    "capAiTitle": "IA",
    "capAutomationTitle": "TIEMPO",
    "capDashboardsTitle": "DATOS",
    "capProductTitle": "SIMPLE",
    "processLabel": "CÓMO TRABAJAMOS",
    "processTitle": "Primero escuchamos. Después construimos.",
    "processIntro": "Te acompañamos en cada paso y te explicamos las decisiones en un lenguaje claro.",
    "stepOneTitle": "Conversamos",
    "stepOneBody": "Nos contás cómo funciona tu negocio, qué te frena y qué te gustaría hacer más fácil.",
    "stepTwoTitle": "Te mostramos una idea",
    "stepTwoBody": "Armamos una propuesta visual para elegir juntos qué mostrar, cómo usarlo y qué incluir.",
    "stepThreeTitle": "Construimos con vos",
    "stepThreeBody": "Desarrollamos la solución, compartimos avances y ajustamos los detalles con tu opinión.",
    "stepFourTitle": "Publicamos y acompañamos",
    "stepFourBody": "La ponemos en marcha, te enseñamos a usarla y revisamos qué se puede mejorar.",
    "workLabel": "EJEMPLOS DE SOLUCIONES",
    "workTitle": "Así podría funcionar para vos.",
    "workIntro": "Son ejemplos para imaginar posibilidades; todavía no son proyectos realizados para clientes.",
    "concept": "Ejemplo conceptual",
    "workOneTitle": "Stock con asistente de IA",
    "workOne": "Preguntá cuánto queda en cada sucursal, pedí un resumen o registrá mercadería desde el chat, confirmando antes de actualizar el stock.",
    "workTwoTitle": "Sitio para profesionales",
    "workTwo": "Mostrá especialidades y perfiles; hacé que cada visitante encuentre a la persona indicada y consulte por WhatsApp.",
    "workThreeTitle": "Panel de tu negocio",
    "workThree": "Reuní tus números más importantes en una pantalla simple y consultá tendencias sin recorrer varias planillas.",
    "aiLabel": "INTELIGENCIA ARTIFICIAL",
    "aiOne": "Abrí el celular.",
    "aiTwo": "Preguntale a tu negocio.",
    "aiBody": "Un asistente puede ayudarte a consultar información, preparar reportes y registrar datos cotidianos. Lo conectamos con la información que tu negocio ya tiene y definimos juntos qué tareas conviene automatizar.",
    "aiUseOne": "Preguntas sobre stock",
    "aiUseTwo": "Reportes a pedido",
    "aiUseThree": "Información por sucursal",
    "aiUseFour": "Consultas sobre tu negocio",
    "aiUseFive": "Cambios con confirmación",
    "terminalQuestion": "¿Cuántos tomates quedan en cada sucursal?",
    "terminalResult": "Ejemplo: quedan 86 kg. Centro tiene 32 kg y Norte 54 kg.",
    "aboutLabel": "POR QUÉ SARAVIA SOFTWARE",
    "aboutOne": "Cerca de tu negocio.",
    "aboutTwo": "Atentos a los detalles.",
    "aboutBody": "Trabajamos con pequeños y medianos negocios que quieren dar un paso digital sin perder su forma de trabajar. Hablamos directamente, explicamos cada propuesta y diseñamos con las personas que van a usarla.",
    "principleOne": "Escuchamos cómo trabajás",
    "principleTwo": "Te mostramos antes de construir",
    "principleThree": "Explicamos sin tecnicismos",
    "principleFour": "Diseñamos para tu día a día",
    "techTitle": "Hablemos de lo que necesitás, en palabras simples.",
    "techOne": "Tu negocio primero",
    "techTwo": "Funciones útiles",
    "techThree": "Diseño a tu gusto",
    "techFour": "IA con propósito",
    "techFive": "Información clara",
    "techSix": "Acompañamiento",
    "contactLabel": "EMPECEMOS POR UNA CHARLA",
    "contactOne": "Contanos cómo trabajás.",
    "contactTwo": "Pensemos qué mejorar.",
    "contactBody": "Una web, una herramienta interna o un asistente para consultar tus datos: conversemos sobre lo que tiene sentido para tu negocio.",
    "contactCta": "Escribinos por WhatsApp",
    "footerExplore": "Explorar",
    "footerSocial": "Redes",
    "footerLegal": "Información legal",
    "footerPrivacy": "Privacidad",
    "footerTerms": "Términos",
    "footerDataDeletion": "Eliminación de datos",
    "footerLine": "Tecnología que se adapta a tu negocio.",
    "heroDemoLabel": "EJEMPLO DE PANEL",
    "heroDemoTitle": "Tu negocio en una pantalla",
    "heroDemoPill": "Vista ilustrativa",
    "heroMetricOne": "Productos",
    "heroMetricTwo": "Sucursales",
    "heroMetricThree": "Stock bajo",
    "heroExample": "Ejemplo",
    "heroChartTitle": "Movimientos de stock",
    "heroChartSubtitle": "Información clara para decidir",
    "heroFloat": "Consultá tus datos",
    "heroCodeOne": "preguntá por tu stock",
    "heroCodeTwo": "obtené una respuesta clara",
    "workMockStock": "Vista de stock",
    "workMockLocations": "En todas tus sucursales",
    "workMockTomato": "Tomates",
    "workMockOrange": "Naranjas",
    "workMockApple": "Manzanas",
    "workMockAsk": "Consultá tu stock",
    "workMockContact": "CONTACTAR PROFESIONAL →",
    "workMockOverview": "Lo importante, de un vistazo",
    "workMockInsights": "Información útil para decidir",
    "terminalLabel": "✳ RESPUESTA",
    "terminalTop": "Saravia Software / asistente de ejemplo",
    "serviceMetaOne": "Stock · IA · Reportes",
    "serviceMetaTwo": "Web · Perfiles · WhatsApp",
    "serviceMetaThree": "Datos · Panel · Consultas"
  },
  "en": {
    "navServices": "Services",
    "navAbout": "About",
    "navProcess": "Process",
    "navWork": "Examples",
    "navContact": "Contact",
    "navCta": "Let's talk",
    "heroOne": "Technology that fits",
    "heroTwo": "your business.",
    "heroBody": "At Saravia Software, we build websites, practical tools and AI for small and medium businesses. First we learn how you work. Then we build something simple and useful around you.",
    "heroCta": "Tell us what you need",
    "heroSecondary": "Explore our services",
    "heroNote": "A clear conversation from the first idea.",
    "heroBottom": "BUILT FOR REAL BUSINESSES",
    "introLabel": "HOW WE THINK",
    "introOne": "Your business has its own way of doing things.",
    "introTwo": "Your technology should too.",
    "introBody": "You do not need a huge platform to solve a specific problem. We take time to understand your day-to-day work and build a solution that fits, with the features you will actually use.",
    "servicesLabel": "HOW WE CAN HELP",
    "servicesTitle": "Solutions for your business.",
    "servicesIntro": "Start with a website that helps people find you or a tool that makes work easier. We will figure it out together.",
    "serviceWebTitle": "Websites that get you found",
    "serviceWeb": "Show what you do, appear in search results and make WhatsApp inquiries easy. We explain content, SEO and visitor data in plain language.",
    "serviceCustomTitle": "Software shaped around you",
    "serviceCustom": "Inventory, bookings or internal tools built around the way you work. Choose what you need to see and which steps feel natural.",
    "serviceAiTitle": "AI assistants",
    "serviceAi": "Ask about your business from your phone, request reports or enter information through chat, with review before changes are saved.",
    "serviceSaasTitle": "Tools that grow with you",
    "serviceSaas": "Start with the essentials and add features when you need them. A solution that fits the size of your operation.",
    "serviceDataTitle": "Clearer business data",
    "serviceData": "See stock, inquiries and results in easy-to-read views, so useful information is there when you need it.",
    "serviceDesignTitle": "Design you feel comfortable with",
    "serviceDesign": "We try every screen with you: what appears first, what things are called and which details matter to your team.",
    "capLabel": "WHAT YOU GET",
    "capWeb": "An online presence that explains what you offer and how to reach you.",
    "capSaas": "Start with what you need; add features as you grow.",
    "capAi": "Ask questions about your business from your phone.",
    "capAutomation": "Spend less time on repetitive tasks.",
    "capDashboards": "Find key numbers without endless spreadsheets.",
    "capProduct": "A tool your team can actually use every day.",
    "capWebTitle": "WEB",
    "capSaasTitle": "GROW",
    "capAiTitle": "AI",
    "capAutomationTitle": "TIME",
    "capDashboardsTitle": "DATA",
    "capProductTitle": "SIMPLE",
    "processLabel": "HOW WE WORK",
    "processTitle": "We listen first. Then we build.",
    "processIntro": "We include you at every step and explain decisions in plain language.",
    "stepOneTitle": "Talk",
    "stepOneBody": "Tell us how your business runs, what gets in the way and what you want to make easier.",
    "stepTwoTitle": "See a first idea",
    "stepTwoBody": "We prepare a visual proposal and decide together what to show, how it works and what to include.",
    "stepThreeTitle": "Build together",
    "stepThreeBody": "We develop the solution, share progress and adjust the details with your feedback.",
    "stepFourTitle": "Launch and support",
    "stepFourBody": "We put it to work, show you how to use it and review what could be improved.",
    "workLabel": "EXAMPLE SOLUTIONS",
    "workTitle": "Picture what this could do for you.",
    "workIntro": "These are examples to show what is possible; they are not completed client projects.",
    "concept": "Concept example",
    "workOneTitle": "Inventory with an AI assistant",
    "workOne": "Ask what is left at each location, request a summary or record new stock in chat, confirming before updating inventory.",
    "workTwoTitle": "Website for professionals",
    "workTwo": "Present specialties and profiles so visitors can find the right person and ask about appointments on WhatsApp.",
    "workThreeTitle": "Your business dashboard",
    "workThree": "Bring your key numbers into one simple view and explore trends without jumping between spreadsheets.",
    "aiLabel": "ARTIFICIAL INTELLIGENCE",
    "aiOne": "Open your phone.",
    "aiTwo": "Ask your business.",
    "aiBody": "An assistant can help you find information, prepare reports and record everyday data. We connect it to information your business already has and decide together which tasks are worth automating.",
    "aiUseOne": "Inventory questions",
    "aiUseTwo": "Reports on request",
    "aiUseThree": "Information by location",
    "aiUseFour": "Questions about your business",
    "aiUseFive": "Confirm changes before saving",
    "terminalQuestion": "How many tomatoes are left at each location?",
    "terminalResult": "Example: 86 kg left. Central has 32 kg and North has 54 kg.",
    "aboutLabel": "WHY SARAVIA SOFTWARE",
    "aboutOne": "Close to your business.",
    "aboutTwo": "Attentive to the details.",
    "aboutBody": "We work with small and medium businesses taking a digital step without giving up the way they work. We speak directly, explain every proposal and design with the people who will use it.",
    "principleOne": "We learn how you work",
    "principleTwo": "We show you a proposal first",
    "principleThree": "We explain things clearly",
    "principleFour": "We design for your daily work",
    "techTitle": "Let's talk about what you need, in plain language.",
    "techOne": "Your business first",
    "techTwo": "Useful features",
    "techThree": "A design that fits",
    "techFour": "Purposeful AI",
    "techFive": "Clear information",
    "techSix": "Ongoing support",
    "contactLabel": "LET'S START WITH A CONVERSATION",
    "contactOne": "Tell us how you work.",
    "contactTwo": "Let's see what could improve.",
    "contactBody": "A website, an internal tool or an assistant to explore your data: let us talk about what makes sense for your business.",
    "contactCta": "Message us on WhatsApp",
    "footerExplore": "Explore",
    "footerSocial": "Social",
    "footerLegal": "Legal information",
    "footerPrivacy": "Privacy",
    "footerTerms": "Terms",
    "footerDataDeletion": "Data deletion",
    "footerLine": "Technology that fits your business.",
    "heroDemoLabel": "EXAMPLE DASHBOARD",
    "heroDemoTitle": "Your business at a glance",
    "heroDemoPill": "Illustrative view",
    "heroMetricOne": "Products",
    "heroMetricTwo": "Locations",
    "heroMetricThree": "Low stock",
    "heroExample": "Example",
    "heroChartTitle": "Inventory activity",
    "heroChartSubtitle": "Clear information for decisions",
    "heroFloat": "Ask about your data",
    "heroCodeOne": "ask about your stock",
    "heroCodeTwo": "get a clear answer",
    "workMockStock": "Inventory overview",
    "workMockLocations": "Across all locations",
    "workMockTomato": "Tomatoes",
    "workMockOrange": "Oranges",
    "workMockApple": "Apples",
    "workMockAsk": "Ask about your inventory",
    "workMockContact": "CONTACT SPECIALIST →",
    "workMockOverview": "What matters at a glance",
    "workMockInsights": "Useful information for decisions",
    "terminalLabel": "✳ RESPONSE",
    "terminalTop": "Saravia Software / example assistant",
    "serviceMetaOne": "Inventory · AI · Reports",
    "serviceMetaTwo": "Web · Profiles · WhatsApp",
    "serviceMetaThree": "Data · Dashboard · Answers"
  }
} as const

export type Language = keyof typeof translations
export type Copy = Record<keyof typeof translations.es, string>
